# Generated by Django 4.1.7 on 2023-04-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_rate_staff_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.bike'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.staff', verbose_name='Испольнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(through='Orders.Operations', to='Orders.services', verbose_name='Услуги'),
        ),
    ]
